### ISSUE TITLE
control uebergabe binary segmentation rec function

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#31]
Wenn ich das richtig verstanden habe ist control eine liste die bei Nutzung von section search bis zur rec function zum fine-tuning weiter gegeben wird. 

1. Du gibst diese immer moeglicherweise unvollstaendig via binary segmentation bis zur REC function bevor du auf NULL values checkst und dann default values einsetzt. Wieso checkst du control nicht auf NULL values beim Aufruf von binary segmentation oder sogar nach dem aufruf von hdcd?

2. Was ist die Motivation dahinter die verschiedenen parameter in einer liste zu uebergeben? Wieso uebergibst du diese nicht einzeln? e.g. hdcd(x, ..... , section_stepsize = 0.5, section_min_points = 3, section_k_sigma = 0). Dies erweitert zwar die anzahl an parameter die hdcd frisst, aber macht die tuning parameter eher zugaenglich (besser verstaendlich wie man tuning control hat). Weiterhin loest dies problem 1 automatisch.

**Comment by MalteLond** [comment]
Merke gerade dass ich bloedsinn geschrieben habe: Du checkst control auf NULL bei jedem aufruf von FindBestSplit.

**Comment by lorenzha** [comment]
Haben wir diskutiert, wenn die params sich ändern für verschiedene Loss Funktionen etc. macht es keinen Sinn sie "hart" in die Funktionsdefinition aufzunehmen. Wenn wir siche rnur Section Search haben werden könnten wir es auch so machen.
