### ISSUE TITLE
warm starts for indiv. loss functions

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#33]
Ich habe mir nochmals Gedanken gemacht bzgl schneller evaluierten Loss functions via updates. Dies ist hauptsaechlich interessant fuer 'groessere', also oft high-dim probleme, mit l1-regularisierung. Hier bieten sich besonders bei line search 'warm starts' an. 

Dies ist jedoch nicht moeglich zu implementieren aehnlich wie beim 1-dim case mit x. Man muesste entweder der Loss function eine reihe von start/end values geben koennen, sodass diese dann intern schnell rechnet und eine reihe von losses zurueck gibt, oder die loss function muesste einen internen cache haben.

**Comment by lorenzha** [comment]
Das mit dem internen Cache habe ich  bei InitSquareLoss so implementiert, das wäre für andere Loss-Functions auch problemlos möglich. Warm-Starts sind sicher eine gute Idee aber ich benutze ja die Meinshausen-Bühlmann approximation (Neighborhood selection). Die ist an sich schon viel schneller als die genaue inverse Covariance Matrix zu schätzen. Da sind meines Wissens aber Warm-starts nicht möglich.
