### ISSUE TITLE
uebergabe von immer kleiner werdenden x

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#34]
Was ist die Motivation dahinter immer x[start:end] zu uebergeben, anstatt immer das volle x im vorherigen environment zu lassen und einfach globale start, end zu uebergeben?

**Comment by MalteLond** [comment]
Generell uebergibst du immer Sachen die im globalen env sowieso gegeben sind und nicht geaendert werden (e.g. delta). Wieso? Man koennte so zum beispiel min_segment_length am anfang ein fuer alle mal festlegen und gut ist.

**Comment by lorenzha** [comment]
Ich fand ursprünglich die Logik einfacher immer den passenden Datenblock weiter zu reichen der dann einfach in die Loss-Funktion geht. Die start, end Geschichte habe ich dann nur eingeführt weil ich die Indizes für die Updates brauche. Man kommt aber wie du richtig feststellst auch nur mit zweiterem aus wenn man alles so umschreibt.

Zu zweiterem: welche Stelle meinst du? Meinst du wenn ich eine Funktion innerhalb einer anderen Funktion aufrufe?

Ich denke entweder will ich explizit machen wo etwas herkommt oder aber das die Funktion auch eigenständig ausgeführt werden kann und nicht nur innerhalb der anderen...

**Comment by lorenzha** [comment]
Inwiefern überschneidet sich das aus deiner Sicht mit #26 ?

**Comment by MalteLond** [comment]
Die loss function ist nun generell so implementiert dass nur start, end uebergeben werden.
