### ISSUE TITLE
n_obs variabel bei cv

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#35]
Wenn wir cv machen, so macht es fuer die skalierung von lambda moeglicherweise sinn, das originale, grosse n_obs zum skalieren zu verwenden, bezueglich delta aber auf keinen fall. Vielleicht sollte man sich darauf festlegen als n_obs die groesse den momentanen folds zu verwenden, um nicht zwei verschiedene n_obs mit sich rum schleppen zu muessen.

**Comment by lorenzha** [comment]
Ich glaube ich habe versucht `n_obs` immer für das globale n zu benutzen und `obs_count` für das lokale im Segment. Tönt mich jetzt auch nicht mehr stimmig, können wir gerne umschreiben.
