### ISSUE TITLE
startrichtung bei section search

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#36]
Wie waehlst du die erste Richtung bei seciton search?

**Comment by lorenzha** [comment]
Siehe ab Zeile 87 in optimizer.R.  Ich starte auf dem längeren Segment. Falls die Länge gleich ist mache ich es abwechselnd (deswegen dieses cache Zeug) damit ich im Grenzfall nicht auf eine bestimmte Seite wandere. Das habe ich mit Solt so besprochen....
