### ISSUE TITLE
ratio regression

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#39]
Verstehe ich das richtig und ist ratio regression einfach die Meinshausen Buehlmann approx? Was genau machst du um den loss zu berechnen?

**Comment by lorenzha** [comment]
Nein die Meinshausen Bühlmann pprox ist nur ein weg wie mit mit glasso für alle p dimensions jeweils einen lasso/elastic net fit macht aber nur einmal die cov matrix berechnet. Man könnte auch mit glmnt p lasso/elastic net fits machen aber dann berechnet glmnet jedes mal die selbe cov matrix neu was computational ziemlich teuer ist. Ratio regression ist einer der Methoden die Solt entwickelt hat, die entscheidenden Code Zeile ist:

`loss <- obs_count * log(colSums(ss) / obs_count)`

Das kommt einfach aus der Überlegung die einzelnen Splits basierend auf der likelihood ratio zwischen einem Model mit zwei Segmenten gegen ein null-Model mit einem Segment durchzuführen. Kann Solt dir besser erklären :)
